name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application with Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t xmas-xchange-app .

    - name: Run Docker Image
      run: docker run xmas-xchange-app -p 5050:5000

  run-postman-tests:
    name: Run Postman Collection Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Newman
      run: |
        sudo npm install -g newman

    - name: Run Postman Collection tests with Newman
      run: |
        newman run postman/xmas-xchange-app.postman_collection.json --delay-request 1000

    - name: Stop and Remove Docker Image
      run: docker rm xmas-xchange-app
