name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application with Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate app/data.json
      run: cp app/data.sample.json app/data.json

    - name: Run docker-compose up
      run: |
        docker compose up -d

    - name: Run docker-compose down
      run: |
        docker compose down

  run-postman-tests:
    name: Run Postman Collection Tests
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate app/data.json
      run: cp app/data.sample.json app/data.json

    - name: Generate Environment Variables
      run: |
        EXPORT name=Adam
        EXPORT phone-number=15556667777
        EXPORT name_fail=Jared
        EXPORT phone-number_fail=1234567890
        EXPORT expected-users-count=7

    - name: Run docker-compose
      run: |
        docker compose up -d

    - name: Install Newman
      run: |
        sudo npm install -g newman

    - name: Run Postman Collection tests with Newman
      run: |
        newman run postman/xmas-xchange-app.postman_collection.json --delay-request 1000

    - name: Run docker-compose down
      run: |
        docker compose down
